spring:
  datasource:
    url: jdbc:mysql://database-1.cw97gboda3y0.us-east-2.rds.amazonaws.com:3306/pDB?createDatabaseIfNotExist=true
    username: root
    password: root1234
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
  application:
    name: profile
security:
  oauth2:
    resource:
      token-info-uri: http://ec2-18-218-236-176.us-east-2.compute.amazonaws.com:9191/oauth/check_token
    client:
      client-id: mobile
      client-secret: pin
server:
  port: 8181
