server:
  port: 9191
spring:
  datasource:
    url: jdbc:mysql://database-1.cw97gboda3y0.us-east-2.rds.amazonaws.com:3306/myDBn1?useSSL=false
    username: root
    password: root1234
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging:
  level:
    org:
      hibernate:
        type: trace