server:
  port: 8787
spring:
  datasource:
    url: jdbc:mysql://database-1.cw97gboda3y0.us-east-2.rds.amazonaws.com:3306/myDBn1?createDatabaseIfNotExist=true
    username: root
    password: root1234
    driver-class-name: com.mysql.jdbc.Driver
  
  mail:
    host: smtp.gmail.com
    port: 587
    username: gtest.ass.sde
    password: Kolkata@1234
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
        
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging:
  level:
    org:
      hibernate:
        type: trace
        
 
 